export const colors = {
  light: {
    background: '#F9FAFB',
    foreground: '#111827',
    'text-secondary': '#4B5563',
    'text-tertiary': '#6B7280',
    surface: '#FFFFFF',
    'surface-elevated': '#FFFFFF',
    border: '#E5E7EB',
    divider: '#F3F4F6',
    accent: '#2563EB',
    'accent-deep': '#1E40AF',
    'accent-bg': '#EFF6FF',
    'accent-foreground': '#FFFFFF',
    'segment-bg': '#F3F4F6',
    'calendar-started': '#DBEAFE',
    'calendar-completed': '#BFDBFE',
    'calendar-heat-1': '#BFDBFE',
    'calendar-heat-2': '#93C5FD',
    'calendar-heat-3': '#60A5FA',
    'chart-bar-light': '#E0E7FF',
    'chevron': '#D1D5DB',
    destructive: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
  },
  dark: {
    background: '#111827',
    foreground: '#F9FAFB',
    'text-secondary': '#9CA3AF',
    'text-tertiary': '#6B7280',
    surface: '#1F2937',
    'surface-elevated': '#1F2937',
    border: '#4B5563',
    divider: '#374151',
    accent: '#2563EB',
    'accent-deep': '#1E40AF',
    'accent-bg': '#1E3A5F',
    'accent-foreground': '#FFFFFF',
    'segment-bg': '#374151',
    'calendar-started': '#172554',
    'calendar-completed': '#1E3A5F',
    'calendar-heat-1': '#1E3A5F',
    'calendar-heat-2': '#2C5EA8',
    'calendar-heat-3': '#4B84E8',
    'chart-bar-light': '#1E3A5F',
    'chevron': '#4B5563',
    destructive: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
  },
} as const;

export type ColorScheme = keyof typeof colors;
export type ColorToken = keyof (typeof colors)['light'];
