/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'rgb(var(--color-background) / <alpha-value>)',
        foreground: 'rgb(var(--color-foreground) / <alpha-value>)',
        'text-secondary': 'rgb(var(--color-text-secondary) / <alpha-value>)',
        'text-tertiary': 'rgb(var(--color-text-tertiary) / <alpha-value>)',
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-elevated': 'rgb(var(--color-surface-elevated) / <alpha-value>)',
        border: 'rgb(var(--color-border) / <alpha-value>)',
        divider: 'rgb(var(--color-divider) / <alpha-value>)',
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
        'accent-deep': 'rgb(var(--color-accent-deep) / <alpha-value>)',
        'accent-bg': 'rgb(var(--color-accent-bg) / <alpha-value>)',
        'accent-foreground': 'rgb(var(--color-accent-foreground) / <alpha-value>)',
        'segment-bg': 'rgb(var(--color-segment-bg) / <alpha-value>)',
        chevron: 'rgb(var(--color-chevron) / <alpha-value>)',
        destructive: 'rgb(var(--color-destructive) / <alpha-value>)',
        success: 'rgb(var(--color-success) / <alpha-value>)',
        warning: 'rgb(var(--color-warning) / <alpha-value>)',
        'zone-fed': 'rgb(var(--color-zone-fed) / <alpha-value>)',
        'zone-fat-burn': 'rgb(var(--color-zone-fat-burn) / <alpha-value>)',
        'zone-ketosis': 'rgb(var(--color-zone-ketosis) / <alpha-value>)',
        'zone-deep-ketosis': 'rgb(var(--color-zone-deep-ketosis) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Inter_400Regular'],
        medium: ['Inter_500Medium'],
        semibold: ['Inter_600SemiBold'],
        bold: ['Inter_700Bold'],
        display: ['DMSans_500Medium'],
        'display-bold': ['DMSans_700Bold'],
        'display-black': ['DMSans_800ExtraBold'],
      },
      borderRadius: {
        card: '16px',
        screen: '40px',
      },
    },
  },
  plugins: [],
};
